### ISSUE TITLE
Allow heaptypes to have a token for superclass identification

### ISSUE THREAD

**Issue by neonene** [neonene/Drafts#1]
As [PEP-630](https://peps.python.org/pep-0630/#type-checking) notes, superclass objects are currently not so easy to access depending on per-module state in multi-phase init extensions, which affects common subclass-checking such as `Py*_Check()`.  They are unreachable in some cases.

This proposes a new `Py_id_static_spec` type slot to store a key in heaptypes, so that a desired superclass can be found through the given type's `tp_mro` or `tp_bases` slot.

# Background

Superclasses are frequently referenced in slot methods (e.g. `nb_add`) for subclass checking.  When implementing a multi-phase init module, a superclass heaptype object is supposed to be placed on a module state, which does not have a good effect on the subclass check:

* Not efficient, walking subtype's MRO twice

  ```
  module = PyType_GetModuleByDef(type, module_def);     // 1st walk
  module_state = PyModule_GetState(module);
  PyType_IsSubtype(type, module_state->My_Super_Type);  // 2nd walk
  ```

* Unsafe during the module finalization

  When a module is finalized, its state can be cleared by the GC before the associated objects and heaptypes are freed.  Even if the module outlives the heaptypes, the types' MRO and module reference can also be cleared[^1].  Currently, there is no secure way to get a particular superclass at the final phase.

# Proposal

### Adding type spec ID to heap types

The heap types will own the pointer to their spec, only when there is an agreement that it cannot be a dangling pointer.  Consequently, the spec's memory address will be usable as the ID to find the class.  Interpreters are supposed to share the same ID globally, since they share the DLL that is supposed not to be unloaded[^2].

### Asking developers for the spec ID

The spec pointer needs to be stored explicitly through the new `Py_id_static_spec` slot:

```c
PyType_Spec foo_spec;

static PyType_Slot foo_slots[] = {
    // Assuming an agreement that the spec is statically allocated.
    {Py_id_static_spec, &foo_spec},
    ...
};

PyType_Spec foo_spec = {
    .slots = foo_slots,
    ...
};
```

The specified value will be verified at the class creation time.

**NOTE:** This proposal does not account for the case where a module holds multiple classes created with the same spec.

# Specification

The `PyHeapTypeObject` struct will have a new internal member, the `(PyType_Spec *) ht_static_spec`, which will not be inherited by subclasses.

The `PyType_FromMetaclass(..., spec, ...)` function family will:

  * Copy the proposed slot's value to the new struct member.
  * Raise a `TypeError` if the specified value (address) does not match the `spec` parameter.

The existing `PyType_GetSlot` function needs to return `NULL` for the new slot ID, as it indicates a hidden member.

### Helpers

  No public function is planned to be added.

  Another subclass check would be:

  1. Walk the subtype's `tp_mro` from the last, or walk the `tp_bases` recursively.
  2. Look for the ID of the desired superclass.

# Backwards Compatibility

One new pointer is added to the `PyHeapTypeObject` struct:

* `ht_static_spec` member, which will not be documented.

One type slot ID is added:

* `Py_id_static_spec` to set `PyHeapTypeObject.ht_static_spec`, which will not be documented. The slot ID needs to be documented together with a helper function usage.  The `PyType_GetSlot` function will not return the actual value for the slot.

# Implementation

A PR has been posted to the Github issue tracker as a `_ctypes` fix, including this proposal: [gh-118139](https://github.com/python/cpython/pull/118139)

# Discussions

Better support for type checking: https://github.com/encukou/abi3/issues/19

[^1]: https://github.com/python/cpython/issues/115874
[^2]: https://github.com/encukou/abi3/issues/19#issuecomment-2076581452

**Comment by neonene** [comment]
> NOTE: This proposal does not account for the case where a module holds multiple classes created with the same spec.

Reconsidering...

**Comment by encukou** [comment]
Sorry that I got to thi so late.

I don't think the pointer needs to be a *spec* per se, neither does it need to be static. It should be a pointer that:
- outlives the class, and
- is “owned” by the module (i.e. it won't clash with other modules).

Of course if it *is* the spec, the module's author will know that and can use it as such :)

I don't think we need a new family of functions. In fact, `{Py_id_static_spec, NULL},` could mean “use the spec rather than `NULL`” (as *absence* of the slot would mean “use NULL"). Or we could do something like `{Py_tp_token, Py_USE_SPEC},` :)

It would be nice to add a “disclaimer” of sorts, anticipating Mark's response:

It should probably be mentioned that there's another possible solution to the issue, along the lines of *immortal per-interpreter singleton modules* (#119663) -- but the mechanism proposed here would still be useful for modules that don't want to be singletons. For even more background: this is the continuation of PEP-489 & later PEPs that aim to add the possibility of C-API modules/classes behaving more like Python equivalents. The “new” approaches are of course more modern and fix several pain points, and so there are efforts to convert *everything* to this style -- but it doesn't mean we can't also start making some things more “static”, if there's appetite for that. But, this proposal isn't about that.

---

And I guess this should be discussed on Discourse rather than here :)
